---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka1
  labels:
    app: kafka1
spec:
  serviceName: kafka1
  replicas: 1
  selector:
    matchLabels:
      app: kafka1
  template:
    metadata:
      labels:
        app: kafka1
    spec:
      containers:
        - name: kafka1
          image: wurstmeister/kafka:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9092 
          env:
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: "kafka1"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zoo1:2181,zoo2:2181
          - name: KAFKA_CREATE_TOPICS
            value: "library-topic:1:1:delete"
          - name: KAFKA_LOG_DIRS 
            value: /kafka/kafka-logs
          - name: KAFKA_BROKER_ID
            value: "1"
          - name: KAFKA_JMX_PORT
            value: "5555"

---

apiVersion: v1
kind: Service
metadata:
  name: kafka1
  labels:
    app: kafka1
spec:
  clusterIP: None
  ports:
    - name: '9092'
      port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    app: kafka1

---


apiVersion: v1
kind: ReplicationController
metadata:
  name: zoo1
spec:
  replicas: 1
  selector:
    app: zoo1
  template:
    metadata:
      labels:
        app: zoo1
    spec:
      containers:
      - name: zoo1
        image: digitalwonderland/zookeeper
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zoo1
        - name: ZOOKEEPER_SERVER_2
          value: zoo2

---


apiVersion: v1
kind: ReplicationController
metadata:
  name: zoo2
spec:
  replicas: 1
  selector:
    app: zoo2
  template:
    metadata:
      labels:
        app: zoo2
    spec:
      containers:
      - name: zoo2
        image: digitalwonderland/zookeeper
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        env:
        - name: ZOOKEEPER_ID
          value: "2"
        - name: ZOOKEEPER_SERVER_2
          value: zoo2

---
apiVersion: v1
kind: Service
metadata:
  name: zoo1
  labels:
    app: zoo1
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    app: zoo1

---
apiVersion: v1
kind: Service
metadata:
  name: zoo2
  labels:
    app: zoo2
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    app: zoo2